export EDITOR=nvim

# Homebrew
if [ -d "/opt/homebrew/bin" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -d "/usr/local/Homebrew/bin" ]; then
  eval "$(/usr/local/bin/brew shellenv)"
elif [ -d "$HOME/.linuxbrew/bin" ]; then
  eval "$("$HOME/.linuxbrew/bin/brew" shellenv)"
elif [ -d "/home/linuxbrew/.linuxbrew/bin" ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# nnn
export GUI=1
export NNN_OPTS="dc"
export NNN_OPENER=/usr/share/nnn/plugins/nuke
export NNN_PLUG='o:fzopen;d:diffs;v:imgview'

# Go
if [ -d "/usr/local/go/bin" ]; then
  export PATH="/usr/local/go/bin:$PATH"
fi

if [ -d "$HOME/go/bin" ]; then
  export PATH="$HOME/go/bin:$PATH"
fi

# Rust
if [ -d "$HOME/.cargo/bin" ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

# Local bin
if [ -d "$HOME/.local/bin" ]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

# Pyenv
if [ -d "$HOME/.pyenv" ]; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
fi

screenshot_full() {
  date=$(date +%Y-%m-%d_%H-%M-%S)
  dir="$HOME/Pictures/Screenshots"
  mkdir -p $dir
  fname="$dir/screenshot-$date.png"
  grim "$fname"
  wl-copy < $fname
}

screenshot_area() {
  date=$(date +%Y-%m-%d_%H-%M-%S)
  dir="$HOME/Pictures/Screenshots"
  mkdir -p $dir
  fname="$dir/screenshot-$date.png"
  grim -g "$(slurp)" "$fname"
  wl-copy < $fname
}
# If we have libpq explicitly installed via homebrew, override the postgres one
if [ -d "${HOMEBREW_PREFIX}/opt/libpq/bin" ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/libpq/bin:$PATH"
fi

# If we have curl installed via homebrew, override the system one
if [ -d "${HOMEBREW_PREFIX}/opt/curl/bin" ]; then
  export PATH="${HOMEBREW_PREFIX}/opt/curl/bin:$PATH"
fi
