# Ignore lines with space
setopt histignorespace

# Disable beep
unsetopt beep

# Keychain options
zstyle :omz:plugins:keychain options --quiet
zstyle :omz:plugins:keychain agents ssh,gpg

# Completion
zstyle ':completion:*' group-name ''
zstyle ':completion:*:*:-command-:*:*' group-order alias builtins functions commands
zstyle :compinstall filename '$HOME/.zshrc'

zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

# Oh-my-zsh settings
DEFAULT_USER="{{ username }}"
COMPLETION_WAITING_DOTS="true"
SHARE_PATH="/usr/share"

bindkey -e

if command -v brew >/dev/null 2>&1; then
	fpath=( "$HOMEBREW_PREFIX/share/zsh/site-functions" "${fpath[@]}" )
	SHARE_PATH="$HOMEBREW_PREFIX/share"
fi
# Antigen
source $SHARE_PATH/antigen/antigen.zsh
antigen use oh-my-zsh

antigen bundle fd
antigen bundle git
antigen bundle wfxr/forgit
antigen bundle keychain
antigen bundle nvm
antigen bundle pyenv
antigen bundle docker
antigen bundle docker-compose
antigen bundle colored-man-pages
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen apply

if command -v fnm >/dev/null 2>&1; then
	eval "$(fnm env)"
fi

if command -v mise >/dev/null 2>&1; then
	eval "$(mise activate zsh)"
fi

if [ -f $SHARE_PATH/nnn/quitcd/quitcd.bash_sh_zsh ]; then
	source $SHARE_PATH/nnn/quitcd/quitcd.bash_sh_zsh
fi

if [ -f $SHARE_PATH/autojump/autojump.zsh ]; then
	source $SHARE_PATH/autojump/autojump.zsh
fi

# Starship prompt
eval "$(starship init zsh)"

# Aliases
alias dirs="dirs -v"
alias wrk='docker run --rm --net=host williamyeh/wrk'
alias dive='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest'
alias docker-here='docker run --rm -it -v $PWD:$PWD --workdir $PWD'
alias docker-aws='docker run --rm -it -v ~/.aws:/root/.aws -e AWS_PROFILE'
alias diffoscope='docker-here registry.salsa.debian.org/reproducible-builds/diffoscope'
alias aws-cli='docker run --rm -it -v ~/.aws:/root/.aws -v $PWD:/aws amazon/aws-cli'
alias dc='docker-compose'
alias tf='terraform'
