# Ignore lines with space
setopt histignorespace

# Disable beep
unsetopt beep

# Keychain options
zstyle :omz:plugins:keychain options --quiet
zstyle :omz:plugins:keychain agents ssh

# Completion
zstyle ':completion:*' group-name ''
zstyle ':completion:*:*:-command-:*:*' group-order alias builtins functions commands
zstyle :compinstall filename '$HOME/.zshrc'

zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

# Oh-my-zsh settings
DEFAULT_USER="pejter"
COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
bindkey -e

# Antigen
source /usr/share/zsh/share/antigen.zsh
antigen use oh-my-zsh

antigen bundle fd
antigen bundle wfxr/forgit
antigen bundle git
antigen bundle keychain
antigen bundle nvm
antigen bundle pyenv
antigen bundle docker
antigen bundle docker-compose
antigen bundle colored-man-pages
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen apply

fpath=( ~/.zfunc "${fpath[@]}" )

if [ -f /usr/share/nnn/quitcd/quitcd.bash_sh_zsh ]; then
    source /usr/share/nnn/quitcd/quitcd.bash_sh_zsh
fi

if [ -f /usr/share/autojump/autojump.zsh ]; then
    source /usr/share/autojump/autojump.zsh
fi

# Starship prompt
eval "$(starship init zsh)"

# Aliases
alias dirs="dirs -v"
alias wrk='docker run --rm --net=host williamyeh/wrk'
alias dive='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest'
alias docker-here='docker run --rm -it -v $PWD:$PWD --workdir $PWD'
alias docker-aws='docker run --rm -it -v ~/.aws:/root/.aws -e AWS_PROFILE'
alias diffoscope='docker-here registry.salsa.debian.org/reproducible-builds/diffoscope'
alias aws-cli='docker run --rm -it -v ~/.aws:/root/.aws -v $PWD:/aws amazon/aws-cli'
alias dc='docker-compose'
